FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY back/pnpm-lock.yaml back/package.json ./

RUN pnpm install --frozen-lockfile

COPY back/ .

EXPOSE 3000

CMD ["pnpm", "start"]